pipelines:
  default:
    - step:
        name: Testing Python 2.7
        image: python:2.7
        script:
          - pip install -r requirements.txt
          - pip install -r tests/requirements.txt
          - python tests/test_suite.py
    - step:
        name: Testing Python 3.4
        image: python:3.4
        script:
          - pip install -r requirements.txt
          - pip install -r tests/requirements.txt
          - python tests/test_suite.py
    - step:
        name: Testing Python 3.5
        image: python:3.5
        script:
          - pip install -r requirements.txt
          - pip install -r tests/requirements.txt
          - python tests/test_suite.py
    - step:
        name: Testing Python 3.6
        image: python:3.6
        script:
          - pip install -r requirements.txt
          - pip install -r tests/requirements.txt
          - python tests/test_suite.py
    - step:
        name: Testing Python 3.7
        image: python:3.7
        script:
          - pip install -r requirements.txt
          - pip install -r tests/requirements.txt
          - python tests/test_suite.py
